/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Mobile android = new Android("Galaxy S10", "Black" , "Samsung");
        Mobile iphone = new IPhone("iPhone 6s", "Rose Gold" , "Apple");
        IPhone iphone2 = new IPhone("iPhone 6s", "Rose Gold" , "Apple");
        Person person = new Person("Zuki");
        IPhoneRobot iphoneRobot = new IPhoneRobot();

        System.out.println(iphone.mobileInfo());
        System.out.println(android.mobileInfo());

        System.out.println(person.makeCall(iphone,"I love iPhone, I love iPhone, I love iPhone, I love iPhone, I love iPhone, I love iPhone, I love iPhone, I love iPhone"));
        System.out.println(person.makeCall(android,"I love iPhone, I love iPhone"));

        System.out.println(iphoneRobot.makeCall(iphone2, "I love iPhone, I love iPhone"));
    }
}